# Site settings
title: Internet of Me by Jerad Acosta
description: > # this means to ignore newlines until "baseurl:"
  A place to reference, recite, rinse and repeat my
  efforts, failures, thoughts and progress, delusions and regressions,
  but mostly a sandbox for whoever I am at the moment.
  Perhaps I'll occasionally enjoy the reminiscing with the castles or
  taking census of the endless games of tic-tac-toe etched in my box.
url: 'http://Jerad.xyz'
baseurl: '/'
# google_analytics: 'you-google-analytcs-ID'
disqus_shortname: 'jeradxyz'

author:
  name: 'Jerad Acosta'
  email: ir@Jerad.XYZ
  twitter_username: irJERAD
  facebook_username: JeradAcosta
  github_username:  irJERAD
  linkedin_username:  JeradAcosta

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']
