# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Internet of Me
email: ir@Jerad.xyz
description: > # this means to ignore newlines until "baseurl:"
  A place to reference, recite, rinse and repeat my
  efforts, failures, thoughts and progress, delusions and regressions,
  but mostly a sandbox for whoever I am now.
  Perhaps I'll occasionally enjoy the reminiscing with the castles or
  taking census of the endless games of tic-tac-toe etched in my box.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Jerad.xyz" # the base hostname & protocol for your site
twitter_username: irJERAD
github_username:  irJERAD

# Build settings
markdown: kramdown
